### ISSUE TITLE
ruby 3 gives raises error wrong number of arguments (given 1, expected 0) on with_config

### ISSUE THREAD

**Issue by mozcomp** [Intrepidd/working_hours#49]
Getting an error when running on ruby 3 ...

ArgumentError: wrong number of arguments (given 1, expected 0)

```
def work_time(start_time, finish_time, units="hour")
  seconds = WorkingHours::Config.with_config(working_hours_config) do
    start_time.working_time_until(finish_time)
  end
end
```

See [write-up](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) on use of keyword arguments in ruby 3  

I believe it just requires an additional double splat argument at the end of the method def ...
```
def with_config(working_hours: nil, holiday_hours: nil, holidays: nil, time_zone: nil, **)
```

**Comment by Intrepidd** [comment]
I think you are passing a hash to the method rather than the expected keyword arguments, the `with_config` only expects keyword arguments, this is why you are getting the error.

If your `working_hours_config` is hash with keys such has `working_hours`, `holidays`, and `time_zone`, your code will probably work if you use the double splat operator to transform the hash into kwargs : 
`WorkingHours::Config.with_config(**working_hours_config)`
